name: Black
on:
  workflow_call:
jobs:
  Black:
    strategy:
      fail-fast: false
      matrix:
        config:
          - container: ghcr.io/steinwurf/black-22:1.0.0
            name: Black 22
    runs-on: [self-hosted, docker, builder]
    name: ${{ matrix.config.name }}
    container:
      image: ${{ matrix.config.container }}
      options: --user 0:0
      volumes:
        - /home/buildbot/.ssh:/root/.ssh
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Black Check
        run: black . --check
